[package]
name = "finalize-stub"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
apple-codesign = "0.27"

[profile.release]
opt-level = 3
lto = true
strip = true
