[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-nostartfiles", "-C", "link-arg=-static", "-C", "link-arg=-no-pie", "-C", "relocation-model=static"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-nostartfiles", "-C", "link-arg=-static", "-C", "link-arg=-no-pie", "-C", "relocation-model=static"]
